language: csharp
solution: IonDotnet.sln
dotnet: 2.1
mono: none

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive


script:
  - git submodule init
  - git submodule update
  - cd IonDotnet.Tests
  - dotnet test -c Release
  - dotnet test
  - cd ..